swagger: '2.0'
info:
  title: Test API
  description: Test API

paths:
  "/player/{id}":
    get:
      description: Returns a Player resource
      produces:
      - application/json
      operationId: getPlayer
      tags:
      - Player
      responses:
        '200':
          description: A player resource.
          schema:
            "$ref": "#/definitions/Player"
    parameters:
    - name: id
      in: path
      description: Identifier of player to retreive
      required: true
      type: string

definitions:

  Player:
    type: object
    properties:
      playerId:
        type: string
      alias:
        type: string
      displayName:
        type: string
      profilePhotoUrl:
        type: string
    required:
    - playerId
    - alias

  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType

  Cat:
    description: A representation of a cat
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        huntingSkill:
          type: string
          description: The measured skill for hunting
          default: lazy
          enum:
          - clueless
          - lazy
          - adventurous
          - aggressive
      required:
      - huntingSkill

  Dog:
    description: A representation of a dog
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        packSize:
          type: integer
          format: int32
          description: the size of the pack the dog is from
          default: 0
          minimum: 0
      required:
      - packSize